# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "@nextcloud/timezones"
SPDX-PackageSupplier = "Richard Steinmetz <richard@steinmetz.cloud>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud-libraries/timezones"

[[annotations]]
path = ["package.json", "package-lock.json", "README.md", "CHANGELOG.md", "renovate.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "resources/timezones/zones.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "tests/assets/**.ics"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019-2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"
