# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Update timezones-data (zones.json)

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 1 * *"

jobs:
  update-timezones:
    runs-on: ubuntu-latest
    name: update-timezones

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Download vzic
        run: git clone https://github.com/libical/vzic.git

      - name: Build vzic
        run: |
          cd vzic
          make -B

      - name: Get python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: '3.10'

      - name: Execute update script
        run: python resources/timezones/update-zones.py --vzic vzic/vzic

      - name: Remove vzic
        run: rm -r vzic

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          token: ${{ secrets.COMMAND_BOT_PAT }}
          commit-message: "fix: update timezones data"
          committer: GitHub <noreply@github.com>
          author: nextcloud-command <nextcloud-command@users.noreply.github.com>
          signoff: true
          branch: automated/noid/update-timezones-data
          base: main
          title: "Update timezones data"
          body: |
            Auto-generated update of timezones data
          labels: |
            3. to review
