# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Update timezones-data (zones.json)

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 1 * *"

jobs:
  update-timezones:
    runs-on: ubuntu-latest
    name: update-timezones

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Download vzic
        run: git clone https://github.com/libical/vzic.git

      - name: Build vzic
        run: |
          cd vzic
          make -B

      - name: Get python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version: '3.10'

      - name: Execute update script
        run: python resources/timezones/update-zones.py --vzic vzic/vzic

      - name: Remove vzic
        run: rm -r vzic

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7
        with:
          commit-message: "fix: update timezones data"
          signoff: true
          branch: automated/noid/update-timezones-data
          base: main
          title: "Update timezones data"
          body: |
            Auto-generated update of timezones data
          labels: |
            3. to review
